services:
  # model list reference: https://huggingface.co/google
  # gpu memory used list reference: https://ai.google.dev/gemma/docs/core
  # docker command reference: https://docs.vllm.ai/projects/recipes/en/latest/Google/Gemma4.html#installing-vllm
  gemma4:
    image: vllm/vllm-openai:gemma4
    container_name: gemma4
    ports:
      - "8000:8000"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host
    shm_size: 16g
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --model google/gemma-4-E2B-it
      --tensor-parallel-size 1
      --max-model-len 32768
      --gpu-memory-utilization 0.90
      --host 0.0.0.0
      --port 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 360
      start_period: 60s

  # environment variables reference: https://docs.openwebui.com/reference/env-configuration/
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - ENABLE_PERSISTENT_CONFIG=False
      
      - WEBUI_AUTH=False

      # - WEBUI_ADMIN_NAME=Admin
      # - WEBUI_ADMIN_EMAIL=admin@example.com
      # - WEBUI_ADMIN_PASSWORD=123

      - OPENAI_API_BASE_URL=http://gemma4:8000/v1
      - OPENAI_API_KEY=dummy
      - DEFAULT_MODELS=google/gemma-4-E2B-it

      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=duckduckgo
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      gemma4:
        condition: service_healthy

volumes:
  open-webui:
